final List<String> allIngredients = [
  "alho",
  "azeite",
  "açúcar",
  "açúcar mascavado",
  "abóbora",
  "bacon",
  "batatas",
  "brócolo",
  "canela",
  "cebola",
  "cenoura",
  "chocolate",
  "coentros",
  "couve",
  "baunilha",
  "cogumelos",
  "café",
  "castanhas",
  "coco",
  "camarão",
  "carne moída",
  "carne de porco",
  "carne de vaca",
  "limão",
  "laranja",
  "lima",
  "leite",
  "pimenta",
  "pimenta em pó",
  "pimenta preta",
  "pimentão",
  "pepino",
  "abacaxi",
  "uva",
  "kiwi",
  "morango",
  "maçã",
  "melancia",
  "melão",
  "manjericão",
  "macarrão",
  "mel",
  "manga",
  "manteiga",
  "noz",
  "noz-moscada",
  "azeitona",
  "oregãos",
  "ovos",
  "chalotas",
  "cebolinho",
  "natas"
  "pão",
  "queijo",
  "repolho",
  "salsa",
  "tangerina",
  "tomate",
  "tomilho",
  "tortilhas de milho",
  "trigo",
  "alface",
  "amendoim",
  "aspargo",
  "atum",
  "avelã",
  "aveia",
  "bacalhau",
  "banana",
  "batata-doce",
  "beterraba",
  "cacau em pó",
  "caldo de legumes"
  "fermento em pó"
  "caju",
  "cebola-roxa",
  "queijo cheddar",
  "queijo cheddar ralado",
  "chouriço",
  "couve-flor",
  "croutons",
  "cominho em pó"
  "creme de leite"
  "damasco",
  "espargos",
  "esparguete",
  "espinafres",
  "farinha",
  "farinha de trigo"
  "feijão",
  "frango inteiro",
  "gema",
  "guacamole",
  "óleo vegetal",
  "hamúrguer",
  "hortelã",
  "lagosta",
  "lula",
  "milho",
  "peito de peru",
  "peito de frango",
  "romã",
  "sal",
  "salmão",
  "salsicha",
  "massa quebrada",
  "massa de lasanha",
  "queijo ricotta",
  "queijo parmesão",
  "queijo parmesão ralado",
  "mozzarella ralada",
  "molho de tomate",
  "molho caesar",
  "paprika",
  "passas",
  "bicarbonato de sódio"
];
